base_url = "https://t3kla.github.io"

title = "T3kla's Portfolio and Blog"
description = "A random place for random thoughts"
author = "Manuel Segura"
default_language = "en"

output_dir = "public"

minify_html = false
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "nord"
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false

[extra]
alias = "Manuel"
copyright = "Â© 2021-2024 Manuel Segura"
